JuulLabs/kable

core/build.gradle.kts, core/src/commonMain/kotlin/Advertisement.kt, core/src/commonMain/kotlin/Central.kt, core/src/commonMain/kotlin/Characteristic.kt, core/src/commonMain/kotlin/Descriptor.kt, core/src/commonMain/kotlin/Error.kt, core/src/commonMain/kotlin/Event.kt, core/src/commonMain/kotlin/IOException.kt, core/src/commonMain/kotlin/Peripheral.kt, core/src/commonMain/kotlin/Scanner.kt, core/src/commonMain/kotlin/Service.kt, core/src/commonMain/kotlin/State.kt, gradle.properties, settings.gradle.kts
Sets up the initial multiplatform project with just the `common` code. Intended to establish the foundation for Kable's public API. More PRs to follow with the platform specific implementations.
Naming generally follows Bluetooth Low Energy naming conventions.
The following guide provides a good overview: https://embedded.fm/blog/ble-roles
1. Create Coroutine scoped `Central`
2. Acquire `Scanner` from `Central`
3. Scan for nearby peripherals by `collect`ing `Advertisement`s from `Scanner`'s `peripherals` `Flow`
4. Use `Central` to convert `Advertisement` to a `Peripheral`
5. Connect to peripheral via `Peripheral`'s `connect` function
6. Communicate with peripheral via `Peripheral` functions
_(example OS X command line app)_
```kotlin
fun main() = runBlocking<Unit> {
val central = …
```
=> Add core module with commonMain

core/src/androidMain/kotlin/BluetoothDevice.kt, core/src/androidMain/kotlin/Observers.kt, core/src/androidMain/kotlin/Peripheral.kt, core/src/androidMain/kotlin/gatt/Callback.kt
Unifies clean up of connection when no longer needed.
It's a bit of a callback dance, but there are a number of causes for disconnection when we have to be sure we've cleaned up the underlying `BluetoothGatt` (via `close`):
- `STATE_DISCONNECTED` from Android (connection dropped, e.g. device went out of range)
- `Peripheral.disconnect` (developer has explicitly requested a disconnect, in `finally` we `dispose` to be sure we clean up if disconnect process is cancelled)
- `Peripheral`'s parent `CoroutineScope` is cancelled
- `Peripheral.connect` is cancelled (e.g. user leaves current screen and connect was being performed via `viewModelScope`)
=> Improve connection handling after a disconnect

core/src/macosX64Main/kotlin/Uuid.kt
The `String` (`UUIDString` property) representation of `CBUUID` will sometimes be in the [16-bit UUID form](https://stackoverflow.com/a/36212021), resulting in `IllegalArgumentException: Uuid string has invalid length` failure.
<details>
<summary>Stacktrace</summary>
```
Uncaught Kotlin exception: kotlin.IllegalArgumentException: Uuid string has invalid length: 180A
at 0   sensortag.kexe                      0x000000010c205ebf kfun:kotlin.Throwable#<init>(kotlin.String?){} + 95 (/Users/teamcity1/teamcity_work/f01984a9f5203417/runtime/src/main/kotlin/kotlin/Throwable.kt:23:37)
at 1   sensortag.kexe                      0x000000010c1ff89d kfun:kotlin.Exception#<init>(kotlin.String?){} + 93 (/Users/teamcity1/teamcity_work/f01984a9f5203417/runtime/src/main/kotlin/kotlin/Exceptions.kt:23:44) …
```
=> Support Core Bluetooth 16-bit UUID representation

.github/CODEOWNERS
Figured it'd be good to have our Apple-platform experts oversee code targeting the 🍎 -platform. 😄
=> Establish code owners for code targeting the Apple platform

core/src/jsMain/kotlin/Peripheral.kt, core/src/jsMain/kotlin/external/BluetoothDevice.kt
Closes #19 
Uses the experimental Web API `watchAdvertisements` to obtain the RSSI value from a peripheral advertisement packet.
=> RSSI support for JS target

.github/workflows/ci.yml, .github/workflows/publish.yml, .github/workflows/snapshot.yml
On every push (commit) Linux and macOS runners run in parallel.
For SNAPSHOTs and publication, only macOS runner is used.
_The publication portion is difficult to test, so may have to create subsequent PRs if there are issues with this configuration._
Closes #27
=> Use macOS runner for CI and publication

core/src/jsMain/kotlin/Peripheral.kt
Fixes which function is called when writing characteristic (JS target).
Thanks to @davidtaylor-juul for spotting this.
=> Fix function used when writing characteristic 'WithoutResponse'

.github/workflows/snapshot.yml
`$default-branch` didn't seem to work.
Calling out `main` branch explicitly instead.
=> Fix SNAPSHOT deployments

core/src/androidMain/kotlin/Peripheral.kt, core/src/jsMain/kotlin/Peripheral.kt, core/src/macosX64Main/kotlin/Peripheral.kt
Was previously using `launch` internally to establish connection. An early failure (before `join` was called) would cause the failure to propagate to the parent scope (rather than the `connect` caller). Switched to using `async` so that failures are properly propagated on call to `await` (within `connect`).
Fixes #44
=> Fix propagation of ConnectionLostException on connect

core/api/core.api, core/src/androidMain/kotlin/Peripheral.kt, core/src/androidMain/kotlin/WriteNotificationDescriptor.kt
Adds ability to configure if the config descriptor for a characteristic is written to when starting/stopping an observation.
> ~I do not have a peripheral that supports notifications on a characteristic that is missing the config descriptor, so I am unable to testes this, nor can I confirm behavior for Apple and JavaScript platforms (which do not have this as configurable).~
**UPDATE:** Tested via Android test app (see https://github.com/JuulLabs/kable/issues/42#issuecomment-757428891 for details).
> ~I suspect that Apple and JavaScript only write to config descriptor if it exists, otherwise many peripherals that violate this requirement (presence of config descriptor) would not work with characteristic notifications.~
**UPDATE:** This assumption was found to be incorrect.
> ~In trying to …
=> Add ability to configure writing to config descriptor for observations

.github/workflows/documentation.yml
The `$default-branch` variable does not seem to work.
=> Use 'main' branch for documentation deployment

core/src/commonMain/kotlin/Exceptions.kt
Oversight where `message` and `cause` were not passed through to the parent `Exception`.
=> Fix BluetoothLeException to have message and cause

core/src/androidMain/kotlin/Scanner.kt, core/src/jsMain/kotlin/Scanner.kt
When `callbackFlow`'s `Channel` is closed due to downstream `Flow` being cancelled then sending to the `Channel` can unexpectedly throw an exception. We suppress the exception, as it is assumed that `Flow` is shutting down anyways.
Closes #67
=> Suppress Scanner advertisement delivery failures

core/src/androidMain/kotlin/Peripheral.kt, core/src/androidMain/kotlin/gatt/Response.kt
The data stream from the `Callback` had the `value` property marked non-`null`, causing a `NullPointerException` to be thrown for `read` operations that were unsuccessful (i.e. GATT status != `GATT_SUCCESS`).
`Connection.execute` already checks that the GATT `status` is `GATT_SUCCESS` and throws `GattStatusException` otherwise. Since we expect Android to always provide non-`null` `ByteArray`s for successful `read` operations, we cast (via `!!`) to non-`null` `ByteArray` to return).
Improves the exception reported in #88.
=> Throw GattStatusException for unsuccessful read operations

README.md
`State` (uppercase **S**) link was trampled by `state` (lowercase). Updated to properly link to the connection `State`.
=> Fix connection State KDoc link

core/api/core.api, core/src/androidMain/kotlin/BluetoothDevice.kt, core/src/androidMain/kotlin/Peripheral.kt
Enables for configuration of transport and PHY of bluetooth connections (Android only).
For more details on the parameters and what they mean, the following links have very helpful information:
- [Bluetooth PHY – How it Works and How to Leverage it](https://punchthrough.com/crash-course-in-2m-bluetooth-low-energy-phy/)
- [Comparison of Bluetooth Basic Rate/Enhanced Data Rate (BR/EDR) vs. Bluetooth low energy (LE) transports](https://electronics.stackexchange.com/a/258897)
---
Closes #61
=> Allow for configuration of transport and PHY on Android

core/src/appleMain/kotlin/Observers.kt
=> Ignore `NotReadyException` when stopping observations on Apple

build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, core/build.gradle.kts, core/src/appleMain/kotlin/Observers.kt, gradle/wrapper/gradle-wrapper.properties
Most notably:
- Kotlin 1.5.0
- Coroutines 1.5.0
- AGP 4.1.3
=> Bump dependency versions

.github/workflows/ci.yml, .github/workflows/documentation.yml, .github/workflows/publish.yml, .github/workflows/release-drafter.yml, .github/workflows/snapshot.yml
Using built in GPG mechanisms ([supported by Gradle](https://docs.gradle.org/current/userguide/signing_plugin.html#using_in_memory_ascii_armored_openpgp_subkeys)) for storing keys as plain text (as GitHub secret), rather than the previously used method of base64'ing the binary key ring.
=> Bump CI dependencies and use in-memory ascii-armored key for signing

.github/workflows/ci.yml
Replaces `push` with `pull_request` CI trigger to allow workflow runs of PRs from forks.
> When you create a pull request from a forked repository to the base repository, GitHub sends the `pull_request` event to the base repository and no pull request events occur on the forked repository.
— [Pull request events for forked repositories](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories)
=> Trigger CI workflow on `pull_request` action

README.md, core/api/core.api, core/src/androidMain/kotlin/Observers.kt, core/src/androidMain/kotlin/Peripheral.kt, core/src/appleMain/kotlin/Observers.kt, core/src/appleMain/kotlin/Peripheral.kt, core/src/commonMain/kotlin/Peripheral.kt, core/src/jsMain/kotlin/Observers.kt, core/src/jsMain/kotlin/Peripheral.kt
Closes #105
Closes #112
Also fixes JavaScript observations to wait until connection is ready. Only users of experimental advertisement support in Chrome would've seen this bug, as using `requestDevice` obtains devices in a connected state, i.e. already ready.
=> Propagate early characteristic changes

core/src/androidMain/kotlin/Peripheral.kt, core/src/commonMain/kotlin/Peripheral.kt
Closes #99
Some peripherals have characteristics that support either notification or indication, when we're observing such a characteristic, we should write to the Client Characteristic Configuration descriptor (CCCD) either to enable notifications **or** indications, **not** both.
We default to only **notifications** if characteristic supports both. This is consistent with the documented behavior of [Core Bluetooth].
[Core Bluetooth]: https://developer.apple.com/documentation/corebluetooth/cbperipheral/1518949-setnotifyvalue
=> Only write indicate or notify to CCCD on Android

README.md, core/src/androidMain/kotlin/Connection.kt, core/src/androidMain/kotlin/Observers.kt, core/src/appleMain/kotlin/Observers.kt, core/src/appleMain/kotlin/Peripheral.kt, core/src/commonMain/kotlin/Peripheral.kt, core/src/jsMain/kotlin/Observers.kt, core/src/jsMain/kotlin/Peripheral.kt
Closes #115
Prior to this change, failures related to observation (e.g. writing to the config descriptor for enabling notifications/indications) could either go through the corresponding `observe` `Flow` or the `connect` function depending on when the `observe` was called — this was confusing and error prone.
Now, all failures related to spinning up the `observe` `Flow` are routed through the corresponding `Flow`, regardless of when the `observe` `Flow` is created.
=> Route observation re-wiring exceptions through `observe` Flows

core/api/core.api, core/src/androidMain/kotlin/Peripheral.kt
Closes #36
Unlike nearly every other BLE request on Android, this one does **not** (or at least it isn't documented to) invoke a function on [`BluetoothGattCallback`](https://developer.android.com/reference/android/bluetooth/BluetoothGattCallback) to indicate when the process is complete (and whether successful or not). It seems you just have to blindly hope it worked. 🤷 
Per [Android ble, requestConnectionPriority not working](https://stackoverflow.com/a/47491885), it is recommended that `requestConnectionPriority` not be called during service discovery. Since Kable's `connect` suspends until connected _and_ services are discovered, it should be safe to call `requestConnectionPriority` anytime after `connect` and not worry about the issue described in the StackOverflow post.
=> Support requesting connection priority on Android

README.md
Referenced "Descriptor D2" when D3 is the one that was supposed to be referenced in the example BLE hierarchy.
=> Fix typo in `descriptorOf` example in project README

.github/workflows/ci.yml
Will allow `publishToMavenLocal` to run on PRs from forks (but without signing) — only performing the signed `publishToMavenLocal` if `SIGNING_KEY` is available (i.e. PRs from organization members).
=> Only sign `publishToMavenLocal` under `JuulLabs` organization

core/src/androidMain/kotlin/BluetoothStateBroadcastReceiver.kt, core/src/androidMain/kotlin/Peripheral.kt, core/src/jsMain/kotlin/Peripheral.kt
Uses a `BroadcastReceiver` to detect when bluetooth has been turned off at the OS level. As an aside, hopefully this addresses #102.
Also changes the name of the private `dispose` function, because I was getting it confused with `Disposable.dispose`, which has very different semantics.
=> Handle bluetooth adapter state changes

core/api/core.api, core/src/androidMain/kotlin/Exceptions.kt, core/src/androidMain/kotlin/Peripheral.kt, core/src/commonMain/kotlin/Exceptions.kt
=> Throw exception when Android's `BluetoothAdapter` is not `On`

README.md, buildSrc/src/main/kotlin/Dependencies.kt, core/build.gradle.kts
Closes #129.
This lifts restricting library consumers to a specific version of Coroutines, with the caveat that library consumers will have to properly configure their Native targets to pull in the `-native-mt` version of Coroutines library.
[`README`](https://github.com/JuulLabs/kable/tree/twyatt/coroutines#multiplatform) has been updated to demonstrate how library consumers can configure Gradle (as recommended [here](https://youtrack.jetbrains.com/issue/KT-43651#focus=Comments-27-4566811.0-0), [here](https://github.com/cashapp/sqldelight/issues/2380#issuecomment-836205507) and [here](https://stackoverflow.com/a/65002984)).
=> Remove dependency on `native-mt` version of Coroutines

core/api/core.api, core/src/androidMain/kotlin/BluetoothDevice.kt, core/src/androidMain/kotlin/Connection.kt, core/src/androidMain/kotlin/Peripheral.kt, core/src/androidMain/kotlin/PeripheralBuilder.kt, core/src/androidMain/kotlin/gatt/Callback.kt, core/src/androidMain/kotlin/gatt/Response.kt
Fixes #86.
Prevents `OutOfOrderGattCallbackException` after peripheral initiated MTU by implementing a dedicated channel for MTU events.
Additionally, exposes `mtu: StateFlow<Int?>` on `AndroidPeripheral`.
=> Handle peripheral initiated MTU changes

README.md
Oversight in the original example updated in #134.
Declaring Coroutines dependency in `common` caused Gradle to fail (when compiling Native targets) with:
<details>
<summary><code>./gradlew runDebugExecutableMacosX64</code></summary>
```
* What went wrong:
Execution failed for task ':app:compileKotlinMacosX64'.
> Could not resolve all files for configuration ':app:macosX64CompileKlibraries'.
> Could not resolve org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1.
Required by:
project :app
> Cannot find a version of 'org.jetbrains.kotlinx:kotlinx-coroutines-core' that satisfies the version constraints:
Dependency path 'sensortag:app:unspecified' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1'
Dependency path 'sensortag:app:unspecified' --> …
```
=> Fix Gradle example configuration in README

README.md
Found a Gradle configuration that works for both application and library Gradle configurations.
Now using (tested) this configuration in https://github.com/JuulLabs/sensortag/pull/10.
=> Specify Kable in `common` source set of example Gradle configuration

core/src/androidMain/kotlin/Observers.kt, core/src/appleMain/kotlin/Observers.kt, core/src/jsMain/kotlin/Observers.kt
Fixes #142.
When `observe` is called, internally it waits until connection is ready before initiating indicate/notify with the peripheral. At which time we increment a counter (of number of subscribers). When performing the reverse operation, we spin down the observation (i.e. inform the OS to disable indicate/notify of characteristic) when the last consumer of an `observe` unsubscribes. If a connection had never been established then upon the last consumer unsubscribing, we'd erroneously attempt to stop the indicate/notify of the characteristic.
By returning `-1` to indicate no previous indicate/notify for that observation has been performed, then we can skip the inverse process (of spinning the observe down).
The crash was due to the fact that we perform characteristic lookups to spin …
=> Only attempt to stop observation if previously observed

buildSrc/src/main/kotlin/Dependencies.kt, core/build.gradle.kts, core/src/jsMain/kotlin/Bluetooth.kt
Was seeing:
```
TypeError: Failed to execute 'requestDevice' on 'Bluetooth': Either 'filters' should be present or 'acceptAllDevices' should be true, but not both.
```
Suspected to be caused by an incompatibility with using an anonymous `object`. This PR instead uses `kotlin-wrappers` library provided `jsObject`.
=> Fix `requestPeripheral` when using Kotlin/JS IR compiler

core/src/jsMain/kotlin/Peripheral.kt
For Web targets, system would hang after the first read. This seems to be the culprit.
=> Fix web listener bug

README.md, core/api/core.api, core/src/androidMain/kotlin/Observers.kt, core/src/androidMain/kotlin/Peripheral.kt, core/src/androidMain/kotlin/Scanner.kt, core/src/androidMain/kotlin/gatt/Callback.kt, core/src/appleMain/kotlin/Peripheral.kt, core/src/appleMain/kotlin/PeripheralDelegate.kt, core/src/commonMain/kotlin/logs/LogMessage.kt, core/src/commonMain/kotlin/logs/Logger.kt, core/src/commonMain/kotlin/logs/Logging.kt, core/src/jsMain/kotlin/Peripheral.kt
Example of setting logging `identifier` to "Example":
<details>
<summary>OS X</summary>
```
...
2021-09-09 02:22:48.788 sensortag.kexe[42195:875213] V/Kable: Example Configuring characteristic observations
2021-09-09 02:22:48.788 sensortag.kexe[42195:875213] I/Kable: Example Connected
2021-09-09 02:22:48.789 sensortag.kexe[42195:875213] D/Kable: Example CentralManager.notify
service: f000aa80-0451-4000-b000-000000000000
characteristic: f000aa81-0451-4000-b000-000000000000
[I/Unknown] Connected
[V/Unknown] Writing gyro period
[I/Unknown] movement → writePeriod → data = 255 (FF)
2021-09-09 02:22:48.790 sensortag.kexe[42195:875213] D/Kable: Example write
service: f000aa80-0451-4000-b000-000000000000
characteristic: f000aa83-0451-4000-b000-000000000000
writeType: WithoutResponse
data: FF
... …
```
=> Add ability to set logging identifier

build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, core/src/androidMain/kotlin/Peripheral.kt
Fixes two separate issues, but they're close enough I think it's okay to couple them.
1. `establishConnection` can throw. Before this PR that exception wouldn't make it to the `logger`, now it will.
2. In the `catch` block of `connectAsync` call `disconnect` instead of `closeConnection`. This should guarantee that we've reached the `Disconnected` state before we actually throw the exception into the connection attempt.
=> Make Android connection failures more robust

core/src/androidMain/kotlin/Peripheral.kt, core/src/appleMain/kotlin/Peripheral.kt, core/src/commonMain/kotlin/Peripheral.kt, core/src/jsMain/kotlin/Peripheral.kt
We were seeing the `IllegalStateException` when calling `connect` from a flow that was being collected from a child scope of the `Peripheral`'s parent scope.
Extremely simplified pseudo-code illustrating the problem:
```kotlin
val scope = CoroutineScope()
val child = scope.createChildScope()
val peripheral = scope.peripheral(..)
peripheral.state.onEach { state ->
if (state is Disconnected) {
// seeing crashes w/ `connect` throwing `IllegalStateException`
peripheral.connect()
}
}.launchIn(child)
scope.cancel()
```
The theory is that there is a potential race condition where the `scope` is being cancelled but the `peripheral`'s state was being updated (and `child` hadn't yet been cancelled).
By removing the explicit check for scope state (in `Peripheral.connect`) allows us to lean on …
=> Have `connect` throw `CancellationException` when scope is cancelled

core/src/jsMain/kotlin/Peripheral.kt
If `connect` fails `disconnectGatt` is called, but there's a pretty decent chance that the callback for `"gattserverdisconnected"` is never triggered. Make sure we move into the `disconnected` state even if that happens.
=> Fix JS connection state stall

.github/workflows/ci.yml, build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, core/build.gradle.kts, core/src/appleMain/kotlin/Advertisement.kt, core/src/appleTest/kotlin/AdvertisementTest.kt, core/src/iosArm32Main, core/src/iosArm32Test, core/src/iosArm64Main, core/src/iosArm64Test, core/src/iosX64Main, core/src/iosX64Test, core/src/macosX64Main, core/src/macosX64Test, gradle.properties
Related to #52.
Configures project to leverage [hierarchical project structure](https://kotlinlang.org/docs/reference/mpp-share-on-platforms.html) for iOS targets (and share code with MacOS target):
```
common 
|-- js 
|-- android 
'-- apple 
|-- ios 
'-- macos 
```
Requires Mac OS X 11 to build due to bumping Kotlin to 1.6.x.
Took the opportunity to bump all dependencies.
Advertisement unit tests were reworked to no longer instantiate `CBPeripheral` objects, as it was causing tests to crash:
<details>
<summary>Crash</summary>
```
> Failed to execute all tests:
:core:iosX64Test: Test running process exited unexpectedly.
Current test: connectingObserves_isAtLeast_connected_is_false
Process output:
2021-11-18 20:50:19.305 test.kexe[5528:24463] *** Terminating app due to uncaught exception …
```
=> Bump Kotlin to 1.6.0 and use hierarchical project structure

core/src/androidMain/kotlin/BluetoothDevice.kt, core/src/androidMain/kotlin/Peripheral.kt
Closes #194
This change will keep the dedicated threads created for BLE communication alive across connections.
By keeping the threads alive (and re-using the same threads across a `Peripheral`'s connections) means we avoid a race-condition that can occur when a connection drops (thus, shutting down the BLE thread) in the middle of an I/O operation.
=> Keep BLE threads alive until `Peripheral` is disposed

.github/workflows/ci.yml, gradle.properties
Using `main-SNAPSHOT` as a default version name makes sense for library users who install to Maven local from the `main` branch; but for other branches it is just confusing. Better to remove the default entirely and let Maven plugin decide default version name (`unspecified` is used when not set).
=> Remove default publication version name

.github/CODEOWNERS
#63 moved where the Apple target's sources were located, this PR simply updates the code owners to match the new location.
=> Fix code owners for Apple source set

core/src/jsMain/kotlin/Bluetooth.kt, core/src/jsMain/kotlin/UUID.kt, core/src/jsMain/kotlin/external/BluetoothUUID.kt
Translate UUID aliases surfaced during discovery into their long-form via `BluetoothUUID.canonicalUUID` so they will be accepted by the `com.benasher44.uuid` library API. See https://webbluetoothcg.github.io/web-bluetooth/#standardized-uuids
Also tweaks the bridging of the `window.navigator.bluetooth` reference as the build environment this was discovered and tested in was tripping over it. (Let me know if that needs to be in a separate PR and I'll move it.)
Closes #206
=> Handle UUID aliases during service discovery

core/src/jsMain/kotlin/Bluetooth.kt
Per https://github.com/JetBrains/kotlin-wrappers/pull/1100, `jsObject` has been removed and `jso` should be used instead.
=> Replace usages of deprecated `jsObject` with `jso`

README.md, core/api/core.api, core/src/androidMain/kotlin/Filter.kt, core/src/appleMain/kotlin/Filter.kt, core/src/commonMain/kotlin/Filter.kt, core/src/commonMain/kotlin/Scanner.kt, core/src/jsMain/kotlin/Filter.kt
#191 helped to commonize the scanner settings implementation, but as reported in https://github.com/JuulLabs/kable/pull/209#issuecomment-998975092, the updates in #191 don't provide a simple migration for the legacy API. The ability to construct common filters was also difficult from common code.
This PR aims to simplify filter creation (when using from common code) and provide deprecated functions for the legacy API.
Closes #230
=> Simplify service filter creation in common code

core/src/commonMain/kotlin/Observers.kt
Cancellations of observations should not be captured/handled by the observation exception handler.
=> Properly propagate observation cancellations

core/build.gradle.kts, core/src/jsMain/kotlin/Bluetooth.kt, core/src/jsMain/kotlin/jso.kt, gradle/libs.versions.toml
Removes [Kotlin/JS extension] dependency in favor of using internal `jso` functions.
The [Kotlin/JS extension] library is upgraded frequently and has had breaking API changes, which would occasionally cause build failures for library consumers who also pulled in mismatched versions of [Kotlin/JS extension].
[Kotlin/JS extension]: https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-extensions
=> Drop Kotlin/JS extensions and use internal `jso` instead

core/src/jsMain/kotlin/Peripheral.kt
When connect fails, wrap the Javascript `Throwable` aka `DOMException` in a regular old Kotlin `Exception` so consumers no longer have to catch `Throwable`.
=> Wrap DOMException

build.gradle.kts, core/build.gradle.kts, gradle/libs.versions.toml
Since Kotlin 1.5.30 added support for Apple Silicon it's now possible to build KMM projects on M1 without Rosetta. However it does require that all dependencies also support it explicitly.
This change should add Apple Silicon support for Kable as well. Unfortunately I haven't been able to test it locally since I'm not sure how to get the whole build working locally.
=> Add Apple Silicon support

core/build.gradle.kts, gradle/libs.versions.toml, log-engine-tuulbox/build.gradle.kts
Replaced deprecated Android Gradle configurations with the corresponding newer version of the directives.
Set target API to `30`, as the default target API defaults to minimum API (see https://github.com/JuulLabs/sensortag/pull/90 for more details).
=> Update Android Gradle configuration and set target API to `30`

core/src/commonMain/kotlin/Observers.kt, core/src/commonMain/kotlin/Peripheral.kt
Fixes a bug where if a device briefly reconnects but then disconnects during rewiring it would end up in the `Connected` state.
=> Propagate observation rewire failures during connection as reconnection failures

core/src/appleMain/kotlin/Peripheral.kt
This adds a disconnect to the peripheral when central manager turns off.  After IOS version 10 there is no didDisconnect callback issued when the Central manager is returned which makes it seem that the device can still be subscribed to.  This adds a disconnect to the peripheral and leaves it up to the client application to decide to reconnect or not. Refs issue #165
=> Add disconnect to Apple peripheral when CBCentralManager turns off

core/src/appleMain/kotlin/CentralManagerDelegate.kt, core/src/appleMain/kotlin/Peripheral.kt
=> Check bluetooth state prior to connecting

core/src/androidMain/kotlin/Scanner.kt
When the scanner returns null on Android, use BluetoothDisabledException to catch in app.
=> Throw `BluetoothDisabledException` instead of `IllegalStateException` on scan

log-engine-tuulbox/build.gradle.kts
Adding macosArm64 target for mac M1 usage.
=> Add `macosArm64` target to `log-engine-tuulbox`

.github/workflows/ci.yml
Running on Ubuntu didn't provide any value as MacOS can run all the checks that Ubuntu can (and the Apple-only checks as well).
=> Simplify CI by only running on MacOS

.github/release-drafter.yml, .github/workflows/release-drafter.yml
Updated release drafts configuration:
- Created labels (`major`, `minor` and `patch`) for auto versioning
- Updated assets for platform sections
---
Assets to be used in release drafts:
| Platform | Image | License | Source |
|:-:|:-:|:-:|:-:|
| Apple | ![apple](https://user-images.githubusercontent.com/98017/186844398-9e8a4bfc-b63d-48dc-b87c-d0d34645295b.png) | [CC4](https://creativecommons.org/licenses/by-sa/4.0/deed.en) | [Wikimedia](https://commons.m.wikimedia.org/wiki/File:Mekuo.png) |
| Android | ![android](https://user-images.githubusercontent.com/98017/186845159-6091676e-3923-4be6-b38f-36ee4a4a6507.png) | [CC3](https://creativecommons.org/licenses/by/3.0/deed.en) | [Wikimedia](https://commons.wikimedia.org/wiki/File:Android_robot.png) |
| JavaScript | …
=> Configure release drafter for auto versioning

.github/workflows/version-labels.yml
PRs must have exactly one of the following labels:
- `major`
- `minor`
- `patch`
- `maintenance` (use for non-code changes, e.g. dependency/build script updates)
- `renovate` _(used by Renovate bot, we shouldn't use this label manually)_
PRs can have as many/few of other labels as desired.
=> Add version label check

core/src/androidMain/kotlin/BluetoothState.kt
Current implementation incorrectly calls `invokeOnClose` when it should be using `awaitClose`.
As a result, when `bluetoothState` subscriber count drops to zero, the following failure will occur:
```
Exception in thread "DefaultDispatcher-worker-1" java.lang.IllegalStateException: 'awaitClose { yourCallbackOrListener.cancel() }' should be used in the end of callbackFlow block.
Otherwise, a callback/listener may leak in case of external cancellation.
See callbackFlow API documentation for the details.
at kotlinx.coroutines.flow.CallbackFlowBuilder.collectTo(Builders.kt:343)
at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at …
```
=> Fix leak/bug in `bluetoothState` flow

core/src/androidMain/kotlin/Advertisement.kt
TLDR: Check and return device name from the advertisement scan record if available. If not return device name as before.
[As I wrote in the discussions](https://github.com/JuulLabs/kable/discussions/400) I had some issues with iBeacon devices. I noticed that on Apple devices I got more advertisements having names than the Android results. I start digging a bit and investigating and stumble upon this:
https://stackoverflow.com/questions/26290640/android-bluetoothdevice-getname-return-null and more especially:
> Advertisement data is how a client BTLE endpoint discovers a service device. A client can request a scan response and get more data. The device name is optional in this data. However, the BTLE spec requires that all Bluetooth Low Energy endpoints support the Generic Access service …
=> Return device name from the scan record when available on Android

README.md, core/build.gradle.kts, core/src/androidMain/AndroidManifest.xml, gradle/libs.versions.toml
[Behavior changes: Apps targeting Android 12](https://developer.android.com/about/versions/12/behavior-changes-12) covers the changes for this target API change. The [Connectivity](https://developer.android.com/about/versions/12/behavior-changes-12#connectivity) section is most relevant for Kable, which covers the various bluetooth permission changes.
=> Bump Android compile/target API to 31

core/src/androidMain/kotlin/Bluetooth.kt, core/src/androidMain/kotlin/broadcastReceiverFlow.kt
`ContextCompat` requires that you specify if the receiver is exported or not. If you don't specify a flag (and use `0`) then it will crash. Fixed by specifying `RECEIVER_NOT_EXPORTED`.
=> Fix regression (crash) introduced in #335

README.md
Adjusted documentation to be in table format (to be more organized/readable).
Rendered markdown [here](https://github.com/JuulLabs/kable/tree/twyatt/android-permissions-doc#android-permissions).
=> Simplify documentation re: Android permissions setup

gradle.properties
According to [KT-42289 comment](https://youtrack.jetbrains.com/issue/KT-42289/Make-the-new-JS-IR-backend-Stable#focus=Comments-27-6622643.0-0), Kotlin/JS IR backend is considered stable w/ 1.8.0, and legacy backend is now deprecated.
Closes #243
=> Drop `LEGACY` JavaScript compiler support

core/api/core.api, core/src/commonMain/kotlin/Bluetooth.kt, core/src/commonTest/kotlin/BluetoothTests.kt
Provides a convenience object for creating UUIDs from short UUIDs (i.e. 16-bit or 32-bit).
The [Bluetooth Core Specification, Vol 3, Part B: 2.5.1 UUID](https://www.bluetooth.com/specifications/specs/?types=adopted&keyword=Core+Specification) states:
> To reduce the burden of storing and transferring 128-bit UUID values, a range of UUID values has been pre-allocated for assignment to often-used, registered purposes. The first UUID in this pre-allocated range is known as the Bluetooth_Base_UUID and has the value 00000000-0000-1000-8000- 00805F9B34FB. UUID values in the pre-allocated range have aliases that are represented as 16-bit or 32-bit values. These aliases are often called 16-bit and 32-bit UUIDs, but each actually represents a 128-bit UUID value.
>
> The full 128-bit value of a …
=> Add `Bluetooth.BaseUuid` utility for short UUIDs

README.md
The new memory model is enabled by default (explicitly enabling it is no longer needed).
=> Remove documentation re: enabling new memory model

README.md
The old memory model is considered deprecated. With version 0.22.0 of Kable, there is no longer support for the old memory model.
=> Remove references to old memory model in documentation

core/api/core.api, core/src/androidMain/kotlin/AndroidPeripheral.kt, core/src/androidMain/kotlin/Observations.kt, core/src/androidMain/kotlin/Peripheral.kt, core/src/appleMain/kotlin/ApplePeripheral.kt, core/src/appleMain/kotlin/CoreBluetoothPeripheral.kt, core/src/appleMain/kotlin/Identifier.kt, core/src/appleMain/kotlin/Observations.kt, core/src/appleMain/kotlin/Peripheral.kt, core/src/jsMain/kotlin/Identifier.kt, core/src/jsMain/kotlin/JsPeripheral.kt, core/src/jsMain/kotlin/Observations.kt, core/src/jsMain/kotlin/Peripheral.kt, core/src/jsMain/kotlin/WebBluetoothPeripheral.kt
No change in functionality, just changing how methods are exposed (via `interface` now rather than concrete classes).
Took the opportunity to rename JavaScript and Apple interfaces to names that more appropriately represent the framework they're built on top of.
=> Introduce platform specific `Peripheral` interfaces

gradle.properties
Warnings about AtomicFU can be quite noisy (and unhelpful). Disabling until [KT-32476](https://youtrack.jetbrains.com/issue/KT-32476) is fixed.
<details>
<summary>Example noisy logs</summary>
```
A compileOnly dependency is used in the Kotlin/Native target 'iosX64':
Compilation: main
Dependencies:
org.jetbrains.kotlinx:atomicfu:0.20.1
Such dependencies are not applicable for Kotlin/Native, consider changing the dependency type to 'implementation' or 'api'.
To disable this warning, set the kotlin.native.ignoreIncorrectDependencies=true project property
A compileOnly dependency is used in the Kotlin/Native target 'macosArm64':
Compilation: main
Dependencies:
org.jetbrains.kotlinx:atomicfu:0.20.1
Such dependencies are not applicable for Kotlin/Native, consider changing the dependency type to …
```
=> Suppress native dependency warnings to quiet AtomicFU warnings

core/src/androidMain/kotlin/Bluetooth.kt
I want to mention two things in advance.
Starting with is the usage of distinctUntilChange(). The used location filter hits more than once when the location tracking is enabled/disabled. Since we are only interested in this change we only emit on enable/disable change.
The second thing is using a function instead of property for isLocationEnabled. Sometimes, also in this context, the usage of property does not work reliably. I also read about that somewhere but cannot remember when and where.
=> Bluetooth availability - monitor location service changes

core/build.gradle.kts, exceptions/build.gradle.kts, log-engine-tuulbox/build.gradle.kts
https://kotlinlang.org/docs/native-target-support.html#deprecated-targets
=> Drop `iosArm32` target

.github/workflows/ci.yml, .github/workflows/publish.yml, core/build.gradle.kts, exceptions/build.gradle.kts, gradle.properties, gradle/libs.versions.toml, log-engine-tuulbox/build.gradle.kts
Newer versions of AGP require JDK 17:
```
An exception occurred applying plugin request [id: 'com.android.library', artifact: 'com.android.tools.build:gradle:null']
> Failed to apply plugin 'com.android.internal.library'.
> Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
Your current JDK is located in /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.18-10/x64/Contents/Home
You can try some of the following options:
- changing the IDE settings.
- changing the JAVA_HOME environment variable.
- changing `org.gradle.java.home` in `gradle.properties`.
```
=> Use JDK 17 on CI

core/api/core.api, core/src/androidMain/kotlin/AndroidPeripheral.kt, core/src/androidMain/kotlin/Peripheral.kt
Needed for checking the state of the Android BLE cache, when making the decision if scanning is needed before reconnecting to a peripheral.
From `AndroidPeripheral.type` KDoc:
> Per [Making Android BLE work — part 1: Clearing the cache](https://medium.com/@martijn.van.welie/making-android-ble-work-part-1-a736dcd53b02#42d8), when `type` is `Unknown`, a scan should be performed before attempting to `connect`.
=> Expose `AndroidPeripheral.type`

core/src/appleMain/kotlin/Peripheral.kt, core/src/commonMain/kotlin/SharedRepeatableAction.kt, core/src/commonTest/kotlin/SharedRepeatableActionTests.kt
Provides a mechanism for allowing an **action** to be performed, and concurrent threads to all watch for the result; while also allowing for the **action** to be cancelled and started over again. _Useful for handling the connect process._
Based on (evolution of) the [`SharedRepeatableTask`](https://github.com/JuulLabs/kable/blob/0.23.0/core/src/jsMain/kotlin/SharedRepeatableTask.kt) class with the primary differentiator: that `SharedRepeatableAction` provides a `CoroutineScope` to the `action` that allows for coroutines to be spawned that **outlive the `action`**.
`SharedRepeatableAction` is available in `common` code but will initially only be used in Apple (and I'll migrate the other platforms over later).
Closes #339.
=> Introduce `SharedRepeatableAction` for handling connect

core/src/appleMain/kotlin/CentralManager.kt, core/src/appleMain/kotlin/Peripheral.kt, core/src/appleMain/kotlin/PeripheralDelegate.kt, core/src/commonMain/kotlin/ObservationEvent.kt
In the spirit of #427, but for Apple platform.
_(small step in resolving #378)_
=> Reduce reliance on `CoroutineScope` within `Peripheral`

.github/workflows/documentation.yml
Noticed that this action has major-only version tags available, which reduces version bump churn.
=> Use major-only version for `github-pages-deploy-action`

core/src/appleMain/kotlin/PeripheralDelegate.kt
Example logs (from SensorTag sample app) shown with the redundant identifier (that this PR removes):
_This occurs because `logger`s are already configured to log the `identifier`:_
https://github.com/JuulLabs/kable/blob/40973d5f50dd4346510f25dcd6296c62053c4cc6/core/src/appleMain/kotlin/PeripheralDelegate.kt#L81
=> Remove redundant logging of peripheral identifier

.github/workflows/ci.yml, .github/workflows/documentation.yml, .github/workflows/publish.yml
Uses `gradle/gradle-build-action` for Gradle runs (to leverage built-in caching configuration).
=> Use `gradle/gradle-build-action@v2` to simplify CI scripts

core/build.gradle.kts, gradle/libs.versions.toml
In #511 AtomicFU was upgraded. In #511, I "cleaned up" the AtomicFU dependency, only to later learn that [AtomicFU plugin doesn't automatically add the dependency for Android source sets](https://github.com/Kotlin/kotlinx-atomicfu/issues/145).
Fixes #519 by explicitly adding the AtomicFU dependency for the Android source set.
=> Fix regression w/ pulling in AtomicFU dependency

.github/workflows/ci.yml, .github/workflows/signing.yml
Performs publication signing for local Maven publication only for commits on `main`. This should allow external contributions to run local Maven publications w/o signing and once merged to `main` will validate that publication signing is configured properly.
Closes #529
=> Only sign local Maven publication on merges to `main`

README.md
Fix typo in android permission (COARSE_LOCATION)
=> Fix typo in Android permission documentation

core/src/androidMain/kotlin/gatt/Callback.kt
=> Properly handle `null`s in deprecated Android BLE callbacks

core/src/appleMain/kotlin/CentralManager.kt, core/src/appleMain/kotlin/CentralManagerDelegate.kt, core/src/appleMain/kotlin/QueueDispatcher.kt, core/src/appleMain/kotlin/ScannerBuilder.kt
This PR allows Apple consumers to take advantage of being woken up in the background to receive BLE events (i.e. device connect/disconnect). 
Also fixes a crash that would occur when the consumer used solicitedServiceUuids--which is needed by the OS to wake up the app.
=> CA-2351: Enable iOS Backgrounding

core/src/androidMain/kotlin/BluetoothAdapter.kt, core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt, core/src/androidMain/kotlin/BluetoothLeScannerAndroidScanner.kt
Pre this fix, `startScan` would fail internally on high/recent OS versions and the scanner callbacks would never be called.
=> Fix Android's scanner behavior when bluetooth is off

core/build.gradle.kts
Since we have `warningsAsErrors`, this warning lint check unnecessarily fails the build.
=> Disable `GradleDependency` Android lint check

core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt
Please see this thread https://developer.apple.com/forums/thread/132488
When we receive CBATTErrorDomain with code 14 is necessary to remove pairing information manually in bluetooth console. The app must advise the user in a friendly way, which is not scope of kable.
With `suspendUntil<State.Connecting.Services>()` the app hangs. So, it is necessary replace by `suspendUntilOrThrow<State.Connecting.Services>().`
In the app we can catch the exception and advising the user correctly:
```
try {
peripheral.connect()
} catch (e: ConnectionLostException) {
if (verifyPlatform() == VerifyPlatform.IOS) {
val st = peripheral.state.first()
if (st is State.Disconnected && (st.status as State.Disconnected.Status.Unknown).status == 14) {
// advise the user correctly
}
}
}
```
Thanks
Closes #334
=> Workaround for CBATTErrorDomain Code=14 "Peer removed pairing information"

core/build.gradle.kts, core/src/androidMain/kotlin/BluetoothDevice.kt, core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt, core/src/androidMain/kotlin/Connection.kt, core/src/androidMain/kotlin/gatt/Callback.kt
Continuation of migration to `SharedRepeatableAction` for Android (see #488 for previous migration of Apple platform).
=> Use `SharedRepeatableAction` for managing connect process

README.md, core/api/core.api, core/src/androidMain/kotlin/BluetoothDevice.kt, core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt, core/src/androidMain/kotlin/Peripheral.kt, core/src/androidMain/kotlin/PeripheralBuilder.kt, core/src/androidMain/kotlin/Reflection.kt
[Martijn van Welie](https://medium.com/@martijn.van.welie) wrote a great article, [Making Android BLE work — part 2](https://medium.com/@martijn.van.welie/making-android-ble-work-part-2-47a3cdaade07), which includes a very informative section on [`autoConnect = true`](https://medium.com/@martijn.van.welie/making-android-ble-work-part-2-47a3cdaade07#7fcf).
~~Making `autoConnect = true` the default, as it is generally easier to manage and will match how Kable behaves on Apple platforms.~~
**UPDATE:** Default now matches the previous behavior, library consumers will need to opt-in to auto-connect.
Library consumers will be able to opt-in to the new behavior via:
```kotlin
val peripheral = scope.peripheral(..) {
autoConnectIf { true }
}
peripheral.connect()
```
Auto-connect is a lambda …
=> Add support for `autoConnect`

core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt, core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt
Unfortunately `SharedRepeatableAction` is proving a bit error prone in its usage. In this particular case, we'd spin up a coroutine to monitor for peripheral disconnection, unfortunately it was prone to race conditions, whereas the resetting of the `SharedRepeatableAction` would propagate cancellation if it saw the disconnect before the `connect` process could itself propagate a failure.
Moving to the end of the connection process allows for failures to always be properly propagated from the `connect` call and _then_ properly monitoring for disconnected state.
=> Monitor disconnected state after connected

core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt
It was an oversight that `setCharacteristicNotificationOrThrow` was not being used — which meant that failures to `setCharacteristicNotification` would fail silently; this PR fixes that.
=> Throw `GattRequestRejectedException` when `setCharacteristicNotification` fails

core/src/androidMain/kotlin/Bluetooth.kt, exceptions/api/exceptions.api, exceptions/src/commonMain/kotlin/Exceptions.kt
Was previously throwing an `IllegalStateException` but that doesn't match the other possible exceptions which inherit from `BluetoothException`.
After this change, the exception tree will look like:
- `Exception`
- `BluetoothException`
- `BluetoothDisabledException`
- `LocationManagerUnavailableException`   _(only thrown on Android)_
- `GattRequestRejectedException`          _(only thrown on Android)_
- `IOException`
- `ConnectionRejectedException`
- `GattStatusException`                   _(only thrown on Android)_
- `NotConnectedException`
- `ConnectionLostException`
- `NotReadyException`
=> Throw `LocationManagerUnavailableException` when `LocationManager` is unavailable

core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt
Accidentally used `this` reference which referred to the logger (not the `Peripheral`, as was intended).
The logger already prints out the peripheral identifier, so including the `Periheral.toString()` in the log message was unnecessary — so, removed `$this` entirely.
=> Fix "disposed" peripheral log message

core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt, core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt
Fixes an edge-case bug that occurs when BLE is turned off in the middle of establishing a connection.
We need to begin monitoring for BLE state _before_ initiating connection, so that it can fail the connect process if BLE is turned off.
=> Monitor bluetooth state before initiating connection

exceptions/src/appleMain/kotlin/Exceptions.kt, exceptions/src/jsMain/kotlin/Exceptions.kt
When a `cause` was provided to `IOException` it was not passed on through to the super `Exception` constructor (essentially dropping the `cause` entirely). This fixes this issue and no longer drops the `cause`.
=> Fix `IOException` to not drop `cause`

core/build.gradle.kts, exceptions/build.gradle.kts, log-engine-tuulbox/build.gradle.kts
[Default hierarchy template](https://kotlinlang.org/docs/multiplatform-hierarchy.html#default-hierarchy-template)
Additional clean up:
- dropped platform specific `kotlin("test-*")`s, as `kotlin("test")` in `commonTest` pulls in the necessary platform specific dependencies
=> Use default hierarchy template

core/src/androidMain/kotlin/gatt/Callback.kt
The docs now explicitly call out that these deprecated callbacks are not memory safe.
Since we still have to use them to support older Android versions, a defensive copy should either:
- guarantee memory safety (if Android doesn't modify the characteristic mid-callback)
- narrow the danger range (if Android can modify the characteristic mid-callback)
Unfortunately I'm not sure which behavior Android has, but I figure this is a win either way -- just a question of total win or partial.
=> Defensive copying in Android legacy, deprecated `BluetoothGattCallback` functions

core/build.gradle.kts, log-engine-tuulbox/build.gradle.kts
We've upgraded AGP beyond the versions that need the workaround.
=> Remove workaround for `jvmToolchain` not being honored pre AGP 8.1.0-alpha09

core/gradle.properties, exceptions/gradle.properties, log-engine-khronicle/gradle.properties, log-engine-tuulbox/gradle.properties
The Maven artifact name defaults to the module name, so the module `gradle.properties` files are superfluous when the `POM_ARTIFACT_ID` matches the module name.
=> Remove explicit `POM_ARTIFACT_ID` configuration

build.gradle.kts, core/build.gradle.kts, gradle/libs.versions.toml, settings.gradle.kts
Now pulling in AtomicFU via `classpath` in `buildscript.dependencies` as it more closely aligns with official [setup instructions].
[setup instructions]: https://github.com/Kotlin/kotlinx-atomicfu?tab=readme-ov-file#apply-plugin
=> Update AtomicFU configuration

build.gradle.kts, core/build.gradle.kts, gradle/libs.versions.toml, settings.gradle.kts
Updates configuration to more closely match [official setup instructions](https://github.com/Kotlin/binary-compatibility-validator?tab=readme-ov-file#setup) (by not configuring/using a shorthand name for the plugin — in other words: no longer using `resolutionStrategy`).
=> Simplify `binary-compatibility-validator` setup

core/build.gradle.kts
Failing a build due to an outdated Android gradle plugin (AGP) is excessive/unnecessary.
=> Disable `AndroidGradlePluginVersion` lint check

core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt, core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt, core/src/jsMain/kotlin/BluetoothDeviceWebBluetoothPeripheral.kt
This PR doesn't attempt any big refactors re. scoping, just makes sure that `dispose`/`finalCleanup` are called near the end of peripheral initialization to avoid unexpected nulls.
=> Fix crash in peripheral `<init>` when parent job is already complete

.github/workflows/ci.yml, .github/workflows/documentation.yml, .github/workflows/publish.yml, .github/workflows/signing.yml
The currently used [`gradle/gradle-build-action`](https://github.com/gradle/gradle-build-action/blob/main/README.md) is deprecated in favor of [`gradle/actions/setup-gradle`](https://github.com/gradle/actions/blob/main/docs/setup-gradle.md).
=> Migrate to `gradle/actions/setup-gradle`

core/api/android/core.api, core/src/androidMain/kotlin/BluetoothLeScannerAndroidScanner.kt, core/src/androidMain/kotlin/ScannerBuilder.kt
It was observed in #654 that using the default blocking send under certain conditions on various devices could result in ANRs being triggered when performing scans.  This PR provides a way for users to opt in to make the Android scanner's `callbackFlow` use a non-blocking `trySend` instead of `trySendBlocking`, with no change to the existing behavior.
Closes #654
=> Provide ability to pre-conflate scanned advertisements

core/gradle.properties, exceptions/gradle.properties, log-engine-khronicle/gradle.properties
We've seen issues for library consumers that manifest in various ways when multiple libraries have the same Maven artifact name.
Most recently, with the K2 upgrade, on the consumer side, we saw failures similar to:
```
e: KLIB resolver: Could not find "com.juul.tuulbox:encoding" in [/Users/ci/Library/Application Support/kotlin/daemon]
```
This occurred because our internal project had an `encoding` module which clashed with Tuulbox's _and_ another of our internal libraries artifacts named `encoding`.
We resolved it by renaming our internal library's Maven artifact to be prefixed.
Additionally, it seems to be standard for libraries to prefix their Maven artifact names, for example: [kotlinx-coroutines-core](https://central.sonatype.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core) …
=> Prefix Maven artifacts with `kable-`

core/src/commonMain/kotlin/Observers.kt
It turns out that any suspending function called after cancelation of the coroutine will itself be canceled. [The kotlin documentation](https://kotlinlang.org/docs/cancellation-and-timeouts.html#run-non-cancellable-block) recommends using `withContext(NonCancellable) {}` in these cases.
Fixes #677
I wanted to write a test for this, but the observation tests don't use any suspend functions so it wasn't clear to me how. It did fix the problem for me, however.
=> Ensure teardown is completed when observation coroutines are canceled

kable-core/src/androidMain/kotlin/BluetoothDevice.kt
Was incorrectly marked as non-nullable, but `connectGatt` may return `null`.
=> Fix nullability of `connectGattCompat` function

README.md, kable-core/src/jsMain/kotlin/Bluetooth.kt, kable-core/src/jsMain/kotlin/Options.kt, kable-core/src/jsMain/kotlin/OptionsBuilder.kt
Brings JavaScript-side API (of specifying filters) in line with the other platforms (see #695) by providing an `Options` builder that contains a `filters { }` bulder.
Closes #723
=> Add `Options` builder

README.md
fixed closing parenthesis in options builder example for Javascript.
=> Fix closing parenthesis in `Options` builder example in README

gradle/libs.versions.toml, kable-core/build.gradle.kts, kable-core/src/jsMain/kotlin/Bluetooth.kt, kable-core/src/jsMain/kotlin/BluetoothLEScanOptions.kt, kable-core/src/jsMain/kotlin/FilterSet.kt, kable-core/src/jsMain/kotlin/jso.kt
Uses `jso` (for creating JavaScript objects) from the JetBrain's [kotlin-wrappers](https://github.com/JetBrains/kotlin-wrappers) library.
Related to #721.
=> Use `jso` from kotlin-wrappers library

.github/workflows/ci.yml, build.gradle.kts
Compilation warnings on CI are too noisy (makes it difficult to find cause of CI failures).
=> Suppress Kotlin compilation warnings on CI

.github/CODEOWNERS
@davidtaylor-juul was being pulled into reviews disproportionately for reviews that didn't necessarily need Core Bluetooth expertise.
Instead, I'll manually add @davidtaylor-juul as a reviewer if I'm uncertain about a Core Bluetooth related change.
=> Remove `davidtaylor-juul` as a CODEOWNER of `appleMain`

kable-core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt, kable-core/src/androidMain/kotlin/Connection.kt, kable-core/src/androidMain/kotlin/gatt/Callback.kt, kable-core/src/androidMain/kotlin/gatt/Response.kt, kable-core/src/appleMain/kotlin/Connection.kt, kable-core/src/appleMain/kotlin/PeripheralDelegate.kt, kable-core/src/commonMain/kotlin/PeripheralBuilder.kt
Re-discovers services when peripheral service database changes.
> [!WARNING]
> Does not re-discover on JavaScript, as event is not supported on Chrome, per [Implementation Status](https://github.com/WebBluetoothCG/web-bluetooth/blob/main/implementation-status.md#gatt-communication-api):
> ![Screenshot 2024-09-19 at 1 03 27 PM](https://github.com/user-attachments/assets/3aff791f-668e-4fec-bf8b-1eb25eb2e75d)
Closes #662
=> Handle when peripheral services change

kable-core/src/androidMain/kotlin/Bluetooth.kt, kable-core/src/appleMain/kotlin/Bluetooth.kt, kable-core/src/commonMain/kotlin/Bluetooth.kt, kable-core/src/jsMain/kotlin/BluetoothAvailability.kt
Per #737, deprecating `Bluetooth.availability`.
=> Deprecate `Bluetooth.availability`

kable-core/api/android/kable-core.api, kable-core/api/jvm/kable-core.api, kable-core/src/androidMain/kotlin/BluetoothDevice.kt, kable-core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt, kable-core/src/androidMain/kotlin/bluetooth/CheckMacAddress.kt, kable-core/src/commonMain/kotlin/GattStatusException.kt, kable-core/src/commonMain/kotlin/Peripheral.kt, kable-core/src/commonMain/kotlin/bluetooth/CheckBluetoothIsSupported.kt
Continuing effort to simplify exception hierarchy (#724).
Inspecting the Android source (at Android API 34):
<details>
<summary><code>BluetoothDevice.java#L3257-3285</code></summary>
</details>
The possible reasons for `BluetoothDevice.connectGatt` returning `null` are:
1. Line 3272: Bluetooth not supported
2. Line 3275: `BluetoothDevice` has a "NULL" MAC address (`00:00:00:00:00:00`)
3. Line 3281 + 3284: `RemoteException` was thrown/caught
This PR now throws appropriate exceptions for the above conditions:
1. `IllegalStateException("Bluetooth not supported")`
2. `IllegalArgumentException("Invalid address: $address")` — _thrown at `Peripheral` construction_
3. `IOException("Binder remote-invocation error")`
> [!TIP]
> More details about `RemoteException` can be found in [Android …
=> Drop `ConnectionRejectedException`

kable-core/src/androidMain/kotlin/Peripheral.deprecated.kt
This fixes the now deprecated `CoroutineScope.peripheral` function to cancel when parent coroutine scope cancels.
=> Have deprecated `CoroutineScope.peripheral` uphold previous behavior

kable-core/api/android/kable-core.api, kable-core/api/jvm/kable-core.api, kable-core/src/androidMain/kotlin/Peripheral.kt, kable-core/src/appleMain/kotlin/Peripheral.kt, kable-core/src/commonMain/kotlin/Peripheral.kt, kable-core/src/jsMain/kotlin/Peripheral.kt
Allows creating a `Peripheral` without specifying the builder configuration.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td>
```kotlin
// OK ✅                           
Peripheral(advertisement) {}
// Error ⛔️
Peripheral(advertisement)
```
</td>
<td>
```kotlin
// OK ✅                           
Peripheral(advertisement) {}
// OK ✅
Peripheral(advertisement)
```
</td>
</tr>
</table>
Closes #791.
=> Make peripheral builder argument optional

kable-core/api/android/kable-core.api, kable-core/api/jvm/kable-core.api, kable-core/src/androidMain/kotlin/Connection.kt, kable-core/src/androidMain/kotlin/bluetooth/CheckBluetoothIsOn.kt, kable-core/src/androidMain/kotlin/scan/ScanError.kt, kable-core/src/appleMain/kotlin/Connection.kt, kable-core/src/appleMain/kotlin/bluetooth/CheckBluetoothIsOn.kt, kable-core/src/commonMain/kotlin/InternalError.kt, kable-core/src/commonMain/kotlin/InternalException.kt, kable-core/src/jsMain/kotlin/BluetoothDeviceWebBluetoothPeripheral.kt, kable-core/src/jsMain/kotlin/BluetoothWebBluetoothScanner.kt, kable-core/src/jsMain/kotlin/Connection.kt, kable-core/src/jsMain/kotlin/RequestPeripheral.kt, kable-core/src/jsMain/kotlin/bluetooth/IsSupported.kt
When an unrecoverable internal failure occurs, a sub-class of [`Error`](https://docs.oracle.com/javase/8/docs/api/?java/lang/Error.html) is more appropriate:
> indicates serious problems that a reasonable application should not try to catch
This is in line with [kotlinx.coroutines' approach](https://github.com/Kotlin/kotlinx.coroutines/blob/6c6df2b850382887462eeaf51f21f58bd982491d/kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt#L131-L133), whereas `CoroutinesInternalError` is a sub-class of `Error` and also asks their library consumers to report the issue.
Closes #789
=> Change `InternalException` to `InternalError`

kable-core/api/android/kable-core.api, kable-core/src/androidMain/kotlin/Peripheral.kt
=> Provide `Peripheral(Identifier)` builder function

kable-core/api/android/kable-core.api, kable-core/api/jvm/kable-core.api, kable-core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt, kable-core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt, kable-core/src/commonMain/kotlin/Peripheral.kt, kable-core/src/jsMain/kotlin/BluetoothDeviceWebBluetoothPeripheral.kt
- Calls maximumWriteValueLength on iOS
- Returns latest know value from onMtuChanged() - 3 on Android, or the default (23 - 3) if the callback haven't been called
- Return default (23 -3) on Web
Closes #729
=> Adds maximumWriteValueLength to Peripheral

README.md
Brendan Weinstein on [Slack](https://kotlinlang.slack.com/archives/CCSFQJD7V/p1734908522284909) caught that the "maven central" badge was using the wrong Maven coordinates for version reference.
Rendered markdown [here](https://github.com/JuulLabs/kable/tree/twyatt/maven-central-badge?tab=readme-ov-file#gradle).
=> Update "maven central" badge to use `kable-core` artifact

kable-core/src/commonMain/kotlin/Observers.kt
=> Create copy of `observations` in `Observers.onConnected`

kable-core/src/commonMain/kotlin/Filter.kt, kable-core/src/commonTest/kotlin/FilterPredicateTests.kt
Closes #814
As seen on the ["Web Bluetooth / Manufacturer Data Filter Sample"](https://googlechrome.github.io/samples/web-bluetooth/manufacturer-data-filter.html?companyIdentifier=0x000D&dataPrefix=03&mask=FF), the actual manufacturer data of a SensorTag (`030000`) is allowed to exceed the length of the specified _filter_ for **manufacturer data** and **mask** (`03` and `FF`, respectively, in the screenshot):
=> Allow for advertisement manufacturer data length to exceed filter data mask length

kable-core/api/jvm/kable-core.api, kable-core/src/androidMain/kotlin/Exceptions.kt, kable-core/src/commonMain/kotlin/GattRequestRejectedException.kt
=> Move `GattRequestRejectedException` to common

README.md, kable-core/api/android/kable-core.api, kable-core/api/jvm/kable-core.api, kable-core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt, kable-core/src/androidMain/kotlin/Peripheral.deprecated.kt, kable-core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt, kable-core/src/commonMain/kotlin/BasePeripheral.kt, kable-core/src/commonMain/kotlin/Peripheral.kt, kable-core/src/jsMain/kotlin/BluetoothDeviceWebBluetoothPeripheral.kt
`Peripheral` no longer implements `CoroutineScope`, instead: it is now a `scope` property.
Per [`CoroutineScope`](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-scope/) documentation:
> Manual implementation of this interface is not recommended, implementation by delegation should be preferred instead.
> `CoroutineScope` should be declared as a property on entities with a well-defined lifecycle that are responsible for launching child coroutines.
To make the `Peripheral` API more explicit, it now implements [`AutoCloseable`](https://kotlinlang.org/api/core/kotlin-stdlib/kotlin/-auto-closeable/) with `close` cancelling the `Peripheral`'s coroutine scope (`scope` property).
=> Provide `Peripheral` `CoroutineScope` via `scope` property

README.md, gradle/libs.versions.toml, kable-core/src/androidMain/kotlin/BluetoothLeScannerAndroidScanner.kt, kable-core/src/commonMain/kotlin/Filter.kt, kable-core/src/commonTest/kotlin/FilterPredicateTests.kt, kable-core/src/jsMain/kotlin/BluetoothLEScanOptions.kt
Closes #854
Updated scan filtering documentation, rendered markdown [here](https://github.com/JuulLabs/kable/tree/twyatt/companyId-only-filter?tab=readme-ov-file#scanning).
=> Allow filtering by company ID only

gradle.properties
```
> Configure project :kable-core
w: ⚠️ Deprecated Gradle Property 'kotlin.native.ignoreIncorrectDependencies' Used
The `kotlin.native.ignoreIncorrectDependencies` deprecated property is used in your build.
Please, stop using it as it is unsupported and may apply no effect to your build.
```
=> Remove deprecated `kotlin.native.ignoreIncorrectDependencies` Gradle option

gradle/libs.versions.toml, kable-core/build.gradle.kts, kable-core/src/androidMain/kotlin/BluetoothLeScannerAndroidScanner.kt, kable-core/src/androidUnitTest/kotlin/com/juul/kable/ScanFiltersTests.kt
Closes #889
Optimizes scan filtering when non-native filter(s) are combined with native filter(s), by favoring native scan filtering and moving non-native supported filters to flow filtering.
Take the following example:
<table>
<tr>
<td align="center"><b>Code</b></td>
<td align="center"><b>Graphical representation</b></td>
</tr>
<tr>
<td>
```kotlin
filter {
match {
service = listOf(Filter.Service(B))
// AND
name = listOf(Filter.Name.Prefix("A_"))
// AND
serviceData = listOf(Filter.ServiceData(..))
}
}
```
</td>
<td>
</td>
</tr>
</table>
This PR will optimize the scan by establishing a native filter for the `Filter.Service` and `Filter.ServiceData` and having the `Filter.Name.Prefix` filtering occur via flow operator.
| Before the PR | After the PR |
|-|-|
| ![Issue 890 …
=> Optimize scan filtering

.github/workflows/pages.yml, build.gradle.kts, gradle.properties, kable-core/build.gradle.kts, kable-log-engine-khronicle/build.gradle.kts
```
> Configure project :
warning: Dokka Gradle plugin V1 is deprecated
Dokka Gradle plugin V1 is deprecated, and will be removed in Dokka version 2.1.0
Please migrate to Dokka Gradle plugin V2. This will require updating your project.
To learn about migrating read the migration guide https://kotl.in/dokka-gradle-migration
```
=> Use Dokka v2 API

kable-core/src/jsMain/kotlin/Connection.kt
If a connection request is made on Web and it fails, sometimes the disconnection callback is never invoked. When this happens the `TimeoutCancellationException` is thrown in the `disconnect` method, but this leaves the state as `Disconnecting` and it never reaches `Disconnected`.
The reason it never reaches `Disconnected` is because the sole place that state change occurs is in the callback, but the callback is never invoked.
This change forces the transistion to `Disconnected` in the `finally` block so that consumers do not get stuck waiting forever. They will still be stuck until the timeout occurs however because we get blocked at line 200 in the main `try` block:
```kotlin
state.filterIsInstance<Disconnected>().first()
```
=> Force update disconnection state

kable-core/api/android/kable-core.api, kable-core/src/androidMain/kotlin/Peripheral.kt
In response to https://github.com/JuulLabs/kable/discussions/936, provides a mechanism of creating a `Peripheral` from an Android native `ScanResult`.
> [!NOTE]
> I don't believe this API will introduce any footguns to consumers, but marking `@ExperimentalApi` to give us time to evaluate.
=> Add ability to create `Peripheral` from `ScanResult`

.github/workflows/ci.yml, .github/workflows/publish.yml, kable-btleplug-ffi/build.gradle.kts, uniffi-plugin/src/main/kotlin/tasks/CopyDynamicLibraryResourcesTask.kt, uniffi-plugin/src/main/kotlin/tasks/UniffiBindgenTasks.kt
Spin up a matrix of runners for the alternative platforms and build `kable-btleplug-ffi`'s jar on each of them. Rip apart the jar, and upload the dynamic library as an artifact. Then, on the main build runner, download those artifacts to a special folder that gets embedded as java resources.
- Rust isn't installed on the Windows 11 ARM runners, so I've skipped that platform for now.
- Building the whole jar for the alternative platforms is inefficient/slow. We could just do a `cargo build --release` and then manually copy the output file to the right place, but the current approach avoids duplicating hard-coded string paths into multiple locations.
- Just building the jar for `kable-btleplug-ffi` doesn't go far enough to guarantee that the FFI exposes the same interface on all platforms. …
=> JVM Publishing

.github/workflows/ci.yml
This will slow down PR CI slightly, but protects against cases where a Rust change has platform specific code that changes the internal Kotlin API.
=> Compile kable-core JVM on all platforms

.github/release-drafter.yml
Adds support for `jvm` platform label in release drafts. Replaces platform logos with emojis; this makes it easier to add additional platforms.
=> Support `jvm` label in release drafts and use emojis for logos

kable-core/api/android/kable-core.api, kable-core/api/jvm/kable-core.api, kable-core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt, kable-core/src/androidMain/kotlin/PeripheralBuilder.kt, kable-core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt, kable-core/src/appleMain/kotlin/Peripheral.kt, kable-core/src/appleMain/kotlin/PeripheralBuilder.kt, kable-core/src/commonMain/kotlin/ObservationEvent.kt, kable-core/src/commonMain/kotlin/Observers.kt, kable-core/src/commonMain/kotlin/PeripheralBuilder.kt, kable-core/src/jsMain/kotlin/BluetoothDeviceWebBluetoothPeripheral.kt, kable-core/src/jsMain/kotlin/PeripheralBuilder.kt, kable-core/src/jvmMain/kotlin/com/juul/kable/PeripheralBuilder.kt, kable-core/src/jvmMain/kotlin/com/juul/kable/btleplug/BtleplugPeripheral.kt
Provides an option as a workaround until #1016 can be tackled.
=> Add `forceCharacteristicEqualityByUuid` peripheral builder option
