JuulLabs/kable

README.md, core/src/androidMain/kotlin/Observers.kt, core/src/androidMain/kotlin/Peripheral.kt, core/src/jsMain/kotlin/Observers.kt, core/src/jsMain/kotlin/Peripheral.kt, core/src/macosX64Main/kotlin/CentralManager.kt, core/src/macosX64Main/kotlin/CentralManagerDelegate.kt, core/src/macosX64Main/kotlin/Peripheral.kt, core/src/macosX64Main/kotlin/PeripheralDelegate.kt
=> Remove majority of logging

README.md
Rendered markdown available [here](https://github.com/JuulLabs/kable/blob/twyatt/readme/README.md#gradle).
=> Add platform specific Gradle configuration to README

build.gradle.kts, core/api/core.api, settings.gradle.kts
Sets up API compatibility checks via [binary-compatibility-validator](https://github.com/Kotlin/binary-compatibility-validator).
=> Setup binary-compatibility-validator

README.md
Rendered markdown available [here](https://github.com/JuulLabs/kable/blob/twyatt/readme/README.md).
=> Update README to link to online KDoc

core/api/core.api, core/src/androidMain/kotlin/Advertisement.kt, core/src/androidMain/kotlin/Scanner.kt, core/src/commonMain/kotlin/Advertisement.kt, core/src/commonMain/kotlin/ManufacturerData.kt, core/src/jsMain/kotlin/Advertisement.kt, core/src/jsMain/kotlin/Bytes.kt, core/src/jsMain/kotlin/Peripheral.kt, core/src/jsMain/kotlin/Scanner.kt, core/src/jsMain/kotlin/external/BluetoothAdvertisingEvent.kt, core/src/jsMain/kotlin/external/JsIterator.kt, core/src/macosX64Main/kotlin/Advertisement.kt, core/src/macosX64Test/kotlin/AdvertisementTest.kt
Expands the Advertisement class to include the majority of the information that can be extracted from BLE advertisement packets.
=> Expanded BLE Advertisement Properties

README.md
https://github.com/JuulLabs/kable/issues/70
=> Simplify platform specific instructions

core/api/core.api, core/src/androidMain/kotlin/Advertisement.kt
=> Expose bond state on Advertisement (Android only)

core/src/androidMain/kotlin/Peripheral.kt
=> Fix expected response type for requestMtu

core/src/jsMain/kotlin/Observers.kt, core/src/jsMain/kotlin/Peripheral.kt
=> Prevent concurrent I/O operations on JavaScript

core/api/core.api, core/src/androidMain/kotlin/Scanner.kt, core/src/appleMain/kotlin/CentralManager.kt, core/src/appleMain/kotlin/Scanner.kt, core/src/commonMain/kotlin/Scanner.kt, core/src/jsMain/kotlin/Scanner.kt
Added scan filtering for IOS, and Android.
Pertains to Issue #22
=> Add support for service filtering during scanning

gradle.properties
=> JavaScript IR Support

core/build.gradle.kts, core/src/appleMain/kotlin/NSData.kt, core/src/iosArm32Main, core/src/iosArm32Test
=> Add `iosArm32` support

core/src/androidMain/kotlin/Peripheral.kt, core/src/appleMain/kotlin/Observers.kt, core/src/appleMain/kotlin/Peripheral.kt, core/src/commonMain/kotlin/State.kt, core/src/jsMain/kotlin/Observers.kt, core/src/jsMain/kotlin/Peripheral.kt
Applies same fix as #154 to Apple and JavaScript targets.
=> Fix characteristic observations on Apple and JavaScript targets

core/src/androidMain/kotlin/Scanner.kt, core/src/jsMain/kotlin/Peripheral.kt
Previously, we were crashing at times when a user toggled Bluetooth during a scan. This should allow that to be cancelled gracefully.
https://jira.juullabs.com/browse/ESC-1869
https://jira.juullabs.com/browse/ESC-1858
=> Improve Advertising Robustness

core/src/appleMain/kotlin/CentralManager.kt, core/src/appleMain/kotlin/CentralManagerDelegate.kt
=> Check scanning state before stopping

core/src/appleMain/kotlin/Peripheral.kt
Added a dedicated connection `CoroutineScope`, so that in-flight connection attempts can be cancelled (via `Job.cancelChildren`) without cancelling the Coroutine that pipes `CentralManager` delegate callbacks to the `Peripheral`'s connection state `Flow`.
Closes #226
=> Prevent connection state monitor from being cancelled on disconnect

README.md
Fixed link URLs and sorted.
Rendered markdown [here](https://github.com/JuulLabs/kable/blob/twyatt/fix-links/README.md).
=> Fix links in project README

core/api/core.api, core/src/androidMain/kotlin/Advertisement.kt
adding scan record byte support,
https://github.com/JuulLabs/kable/issues/356
=> Add property for retrieving raw bytes of scan record

core/src/commonMain/kotlin/Observation.kt, core/src/commonMain/kotlin/Observers.kt
=> Reset observation state on connect if there are no subscribers

core/api/core.api, core/src/androidMain/kotlin/Peripheral.kt, core/src/appleMain/kotlin/Peripheral.kt, core/src/commonMain/kotlin/Peripheral.kt, core/src/jsMain/kotlin/Peripheral.kt
=> Surface bluetooth device name

core/src/jsMain/kotlin/Bluetooth.kt
=> Enforce lowercase UUIDs for Web BLE filters

core/api/core.api, core/src/androidMain/kotlin/Advertisement.kt, core/src/appleMain/kotlin/Advertisement.kt, core/src/commonMain/kotlin/Advertisement.kt, core/src/jsMain/kotlin/Advertisement.kt
=> Add property to `Advertisement` to indicate if peripheral is connectable

core/src/androidMain/kotlin/gatt/Response.kt
=> Replace deprecated `inline` class modifier with `value`

core/api/core.api, core/src/androidMain/kotlin/AndroidPeripheral.kt, core/src/androidMain/kotlin/Peripheral.kt
=> Add `address` property to `AndroidPeripheral`

core/src/androidMain/kotlin/BluetoothDevice.kt, core/src/androidMain/kotlin/Connection.kt, core/src/androidMain/kotlin/Peripheral.kt, core/src/androidMain/kotlin/gatt/Callback.kt, core/src/appleMain/kotlin/CentralManager.kt, core/src/appleMain/kotlin/Connection.kt, core/src/appleMain/kotlin/Peripheral.kt
=> Fix BLE I/O cancellation handling

core/src/appleMain/kotlin/Connection.kt, core/src/appleMain/kotlin/Peripheral.kt
I believe `Semaphore` was previously used because the `Mutex` could deadlock under the old memory model.
=> Replace `Semaphore` with `Mutex` in `Connection`

core/src/appleMain/kotlin/CentralManager.kt, core/src/appleMain/kotlin/Connection.kt, core/src/appleMain/kotlin/Peripheral.kt
The internals of `Peripheral` now lean more on structured concurrency (disposal of objects uses coroutine lifecycle mechanisms and parent-child relationships).
=> Simplify internal lifecycle of `Peripheral`

core/api/core.api, core/src/androidMain/kotlin/Peripheral.kt, core/src/appleMain/kotlin/Identifier.kt, core/src/appleMain/kotlin/Peripheral.kt, core/src/commonMain/kotlin/Identifier.kt, core/src/commonMain/kotlin/Peripheral.kt, core/src/jsMain/kotlin/BluetoothDeviceWebBluetoothPeripheral.kt, core/src/jsMain/kotlin/Identifier.kt
=> Promote `identifier` to property on `Peripheral` interface

core/api/core.api, core/src/androidMain/kotlin/ScanResultAndroidAdvertisement.kt, core/src/appleMain/kotlin/CBPeripheralCoreBluetoothAdvertisement.kt, core/src/appleMain/kotlin/CoreBluetoothAdvertisement.kt, core/src/commonMain/kotlin/Advertisement.kt, core/src/jsMain/kotlin/BluetoothAdvertisingEventWebBluetoothAdvertisement.kt, core/src/jsMain/kotlin/WebBluetoothAdvertisement.kt
=> Add identifier property to Advertisement object

README.md
=> README.md: fix spelling error

core/src/androidMain/kotlin/BluetoothLeScannerAndroidScanner.kt
=> Remove `flowOn(Main.immediate)` from `advertisements`

log-engine-tuulbox/build.gradle.kts
See [Changes to Android Target support](https://kotlinlang.org/docs/whatsnew19.html#changes-to-android-target-support) for more details.
=> Use new `androidTarget` Gradle DSL

README.md
Rendered markdown [here](https://github.com/JuulLabs/kable/tree/twyatt/auto-connect-documentation#autoconnect).
=> Add documentation about `autoConnectIf`

core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt
Fixes an edge case: when device goes out-of-range during an in-flight connection attempt _and_ `disconnect` is called then Android doesn't send a disconnected event to the `Callback` — this would cause us to never dispose (`close`) the GATT object and stall forever in the `disconnect` function (waiting for `Disconnected` state).
Now, when `disconnect` is called, the `connectAction` is explicitly cancelled if we're not yet connected. In the connection action lambda we catch the `CancellationException` and unwrap it to propagate it through the `connect` function _and_ `closeConnection` is called which explicitly disposes of the GATT object.
=> Cancel in-flight connection attempt on `disconnect`

gradle/libs.versions.toml, log-engine-khronicle/api/log-engine-khronicle.api, log-engine-khronicle/build.gradle.kts, log-engine-khronicle/gradle.properties, log-engine-khronicle/src/commonMain/kotlin/logs/KhronicleLogEngine.kt, settings.gradle.kts
Deprecates but does not remove Tuulbox logger.
=> Log engine for Khronicle logging

core/api/android/core.api, core/build.gradle.kts, core/src/androidMain/kotlin/AndroidAdvertisement.kt, core/src/androidMain/kotlin/ScanResultAndroidAdvertisement.kt
=> Make `AndroidAdvertisement` parcelable

core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt
=> Watch for connection loss during connect

README.md
Rendered markdown [here](https://github.com/JuulLabs/kable/tree/twyatt/gradle-doc?tab=readme-ov-file#gradle).
=> Update Gradle documentation w/ new Maven coordinate

core/src/appleMain/kotlin/CBPeripheralCoreBluetoothAdvertisement.kt
=> Cast to `NSNumber` for determining if advertisement is connectable

README.md
Commit 06402413693844653ccc2dff5ec0db3d3f4ca8d1 moved the location of `AndroidManifest.xml. This PR adjusts sources to changes.
=> Update `AndroidManifest.xml` reference

README.md, kable-core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt, kable-core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt, kable-core/src/commonMain/kotlin/SharedRepeatableAction.awaitConnect.kt, kable-core/src/commonMain/kotlin/SharedRepeatableAction.kt, kable-core/src/jsMain/kotlin/BluetoothDeviceWebBluetoothPeripheral.kt
=> Improve exception message when attempting to `connect` a cancelled peripheral

kable-core/api/android/kable-core.api, kable-core/api/jvm/kable-core.api, kable-core/src/androidMain/kotlin/Connection.kt, kable-core/src/androidMain/kotlin/external/Constants.kt, kable-core/src/androidMain/kotlin/gatt/Callback.kt, kable-core/src/androidMain/kotlin/gatt/Response.kt, kable-core/src/androidMain/kotlin/logs/LogMessage.kt, kable-core/src/commonMain/kotlin/GattStatusException.kt, kable-core/src/commonMain/kotlin/android/GattStatus.kt
=> Expose Android GATT status `Int` on `GattStatusException`

kable-core/src/appleMain/kotlin/Uuid.kt
=> Support 32-bit (8 hex characters) `CBUUID`s

kable-core/src/commonMain/kotlin/SharedRepeatableAction.kt
Unfortunately I was unable to reproduce it outside our internal project, but found that in some configurations/environments the `Mutex` lock lambda will enter continuously (forever) — essentially locking up the web page. Switching to AtomicFu's re-entrant lock fixes the issue.
> [!NOTE]
> Although the issue was only ever observed on JavaScript, the change applies to all platforms as I believe it is a safe change to make.
https://github.com/JuulLabs/kable/blob/05e2f19fc72599f3dc28247219e2832c33092357/kable-core/src/commonMain/kotlin/SharedRepeatableAction.kt#L73-L77
A debug log was added between lines 73 and 74, after execution of `create` (on line 76), the log was seen repeating forever.
=> Fix `Mutex` infinite loop in `SharedRepeatableAction`

kable-core/src/appleMain/kotlin/CBPeripheralCoreBluetoothAdvertisement.kt
=> Fix handling of manufacturer code

gradle/libs.versions.toml, kable-core/build.gradle.kts, kotlin-js-store/yarn.lock
Thanks to @curioustechizen for calling this out in #957.
=> Remove unused `kotlinx.datetime` dependency

kable-core/src/androidMain/kotlin/Identifier.kt, kable-core/src/androidMain/kotlin/Peripheral.kt
=> Allow for MAC address to be lowercase
